Login/urls.py
from django.urls import path





from .views.Instructor.instructor_sessie_view import  AddSessieAPIView_2,  UpdateSessieAPIView
from.views.Instructor.instructor_student_view import AddStudentAPIView
from.views.Instructor.instructor_material_view import MateriaalListApiView, IndividualMateriaalListApiView, CreateMateriaalAPIView
from .views.Instructor.instructor_helpers_view import GeneralContextAPIView


from .views.Student.student_sessie_view import SessieListViewAPI 
from .views.Student.student_student_view import StudentListAPI, StudentDetailAPI
from.views.Student.student_helpers_view import create_rating, create_leerling_with_secret_code, check_leerling_status, get_all_subjects



app_name='Login'

urlpatterns = [


    #api Student Portal
    path('api/sessie/', SessieListViewAPI.as_view(), name='api_sessie'),
    path('api/student/', StudentListAPI.as_view(), name='api_student'),     #What kind of view is this? Is this safe?
    path('api/student_detail/', StudentDetailAPI.as_view(), name='api_student_detail'),
    path('api/student_detail/<int:pk>/', StudentDetailAPI.as_view(), name='student-detail-by-pk'),
    path('api/create_rating/', create_rating, name='api_create_rating'),
    path('api/vakken/', get_all_subjects, name='api_get_all_subjects'),
    path('api/create_leerling/', create_leerling_with_secret_code, name='api_create_leerling_with_secret_code'),
     path('api/check_leerling_status/', check_leerling_status, name='check-leerling-status'),


    #api Instructor Portal
    path('api/add_sessie/', AddSessieAPIView_2.as_view(), name='api_add_sessie_2'),
    path('api/add_student/', AddStudentAPIView.as_view(), name='api_add_student'),
    path('api/general_context/', GeneralContextAPIView.as_view(), name='api_general_context'),
    path('api/materiaal_all/', MateriaalListApiView.as_view(), name='api_materiaal_all_context'),
    path('api/materiaal_ind/', IndividualMateriaalListApiView.as_view(), name='api_materiaal_all_context'),
    path('api/add_materiaal/', CreateMateriaalAPIView.as_view(), name='api_add_materiaal'),
    path('api/sessies/<int:sessie_id>/', UpdateSessieAPIView.as_view(), name='update_sessie'),



  

]

Werknemersapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.http.response import HttpResponse
from . import views



urlpatterns = [
   
  
    path('Login/',include("Login.urls")),
    path('api/auth/', include('authentication.urls')),
    path('admin/', admin.site.urls),
    path('',views.redirect_to_login,name='home'),
    path('accounts_2/',include('allauth.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    
    path("__reload__/", include("django_browser_reload.urls")),
 
]

Login/models.py
import datetime
from distutils.command import sdist
from turtle import mode
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from django.db import models
from pkg_resources import DistInfoDistribution
from rest_framework.views import APIView
from django.db.models import Q
from django.utils.crypto import get_random_string


import datetime
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Model representing a school
class School(models.Model):
    naam = models.CharField(max_length=30)  # Name of the school
    grootte = models.IntegerField()  # Size (number of students or other metric) of the school
    secret_code = models.CharField(max_length=6, default="f2AjB89")  # Secret code for registering students"  )
    def __str__(self) -> str:
        return self.naam

# Model representing an education level or grade
class Niveau(models.Model):
    naam = models.CharField(max_length=50)  # Name of the level or grade
    scholen = models.ManyToManyField(School, related_name='niveaus')  # Schools that have this level

    def __str__(self):
        return self.naam

# Model representing a subject or course
class Vak(models.Model):
    naam = models.CharField(max_length=50)  # Name of the subject
    niveaus = models.ManyToManyField(Niveau, related_name='vakken')  # Levels that have this subject
    
    def __str__(self):
        return self.naam

# Model representing a class in a school
class Klas(models.Model):
    naam = models.IntegerField()  # Class identifier or name
    niveaus = models.ManyToManyField(Niveau, related_name='klassen')  # Levels associated with this class
    vakken = models.ManyToManyField(Vak, related_name='klassen')  # Subjects taught in this class

    def __str__(self):
        return str(self.naam)

# Model representing a mentor or tutor
class Begeleider(models.Model):
    gebruiker = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)  # User account of the mentor
    scholen = models.ManyToManyField(School, related_name='begeleiders')  # Schools the mentor is associated with

    def __str__(self) -> str:
        return str(self.gebruiker)

# Model representing a team leader
class Teamleider(models.Model):
    gebruiker = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)  # User account of the team leader
    school = models.ForeignKey(School, on_delete=models.CASCADE)  # School the team leader belongs to

    def __str__(self) -> str:
        return str(self.gebruiker)

# Model representing a student
class Leerling(models.Model):
    # Student's basic details
    naam = models.CharField(max_length=30)
    achternaam = models.CharField(max_length=30)
    email = models.EmailField()
    school = models.ForeignKey(School, null=True, on_delete=models.CASCADE)
    klas = models.ForeignKey(Klas, null=True, on_delete=models.SET_NULL)
    niveau = models.ForeignKey(Niveau, null=True, on_delete=models.SET_NULL)
    gebruiker = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    vakken = models.ManyToManyField(Vak, through='LeerlingVakRating', related_name='leerlingen')  # Subjects the student is enrolled in
    
    def __str__(self):
        return f'{self.naam} {self.achternaam}'

    def get_absolute_url(self):
        return reverse('Leerling_detail', kwargs={'pk': self.pk})

# Model for storing student's rating or feedback for a particular subject
class LeerlingVakRating(models.Model):
    MOEILIJKHEIDSKEUZES = [(i, str(i)) for i in range(1, 11)]  # Choices for difficulty ratings
    leerling = models.ForeignKey(Leerling, on_delete=models.CASCADE)
    vak = models.ForeignKey(Vak, on_delete=models.CASCADE)
    cijfer = models.IntegerField(choices=MOEILIJKHEIDSKEUZES, default=5)  # Numeric rating for difficulty
    beschrijving = models.TextField(default='Schrijf hier een beschrijving van het vak')  # Description or feedback
    
    class Meta:
        unique_together = ['leerling', 'vak']  # Ensure a unique rating for each subject per student
    
    
    
class LeerlingVakRatingHistory(models.Model):
    leerling_vak_rating = models.ForeignKey(LeerlingVakRating, on_delete=models.CASCADE) # wanneer je een rating verwijderd, verwijder je ook de history
    cijfer = models.IntegerField(default=5)
    beschrijving = models.TextField()
    date_recorded = models.DateField(auto_now_add=True)
    
    def vak_name(self):
        return self.leerling_vak_rating.vak.naam
    vak_name.short_description = "Vak Name"
# Model representing learning materials
class Materiaal(models.Model):
    # Material details
    titel = models.CharField(max_length=100)
    bestand = models.FileField(upload_to='materialen/')
    vak = models.ForeignKey(Vak, on_delete=models.CASCADE)
    niveau = models.ForeignKey(Niveau, on_delete=models.CASCADE)
    klas = models.ForeignKey(Klas, on_delete=models.CASCADE)
    omschrijving = models.TextField(default='Schrijf de beschrijvingen zo uitgebreid mogelijk. We gaan dit later verwerken in een zoeksysteem')  # Description of the material
    leerling = models.ForeignKey(Leerling, null=True, blank=True, on_delete=models.SET_NULL, related_name='persoonlijk_materiaal')  # If the material is specific to a student

# Model representing a session between a student and a mentor/tutor
class Sessie(models.Model):
    # Choices for different ratings
    INZICHT_CHOICES = [(i, str(i)) for i in range(1, 6)]
    KENNIS_CHOICES = [(i, str(i)) for i in range(1, 6)]
    WERKHOUDING_CHOICES = [(i, str(i)) for i in range(1, 6)]
    
    # Session details
    Leerling = models.ForeignKey(Leerling, on_delete=models.CASCADE)
    begeleider = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)  # Tutor/mentor for the session
    inzicht = models.IntegerField(choices=INZICHT_CHOICES)  # Insight rating
    kennis = models.IntegerField(choices=KENNIS_CHOICES)  # Knowledge rating
    werkhouding = models.IntegerField(choices=WERKHOUDING_CHOICES)  # Work attitude rating
    extra = models.TextField()  # Additional notes
    datum = models.DateField(default=datetime.date.today())  # Date of the session
    school = models.ForeignKey(School, on_delete=models.CASCADE, null=True, blank=True)
    vak = models.ForeignKey(Vak, null=True, on_delete=models.SET_NULL)  # Subject of the session

    def __str__(self):
        return f'Sessie {self.pk} ({self.Leerling}, {self.begeleider})' 

    def get_absolute_url(self):
        return reverse('Sessie_detail', kwargs={'pk': self.pk})

Login/forms.py
from django import forms
from .models import Leerling, Sessie, Materiaal
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import TextInput



class StudentForm(forms.ModelForm):
    class Meta:
        model = Leerling
        fields = '__all__'

class SessieForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(SessieForm, self).__init__(*args, **kwargs)
        self.fields['Leerling'].widget = forms.Select()
        
    class Meta:
        model = Sessie
        fields = '__all__'
        exclude=['school','begeleider']

class SessieFormUpdate(forms.ModelForm):
    class Meta: 
        model = Sessie
        fields = '__all__'


class MateriaalForm(forms.ModelForm):
    class Meta:
        model = Materiaal
        fields = '__all__'



class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'nav'}))

Login/views/sessie.py
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

# Relative imports for serializers and models
from ..serializers import SessieSerializer, SessieSerializer_2
from ..models import Leerling, Sessie

#############################################################################################################
############################################## ADD Session #################################################
#############################################################################################################


@authentication_classes([JWTAuthentication])
@permission_classes([IsAuthenticated])
class AddSessieAPIView(APIView):
    def post(self, request):
        # Create a mutable copy of the request data
        data = request.data.copy()
        
        print("Request Data:", data)
        
        # Extract the Leerling ID from the request data
        leerling_id = data.pop('Leerling')[0]  # QueryDict values are lists, so we take the first element
        # Fetch the Leerling instance using the provided ID
        leerling_instance = Leerling.objects.get(id=leerling_id)
        
        # Update the request data with the Leerling instance
        data['Leerling'] = leerling_instance.id
        
        serializer = SessieSerializer(data=data)
        print(serializer.is_valid())
        
        if serializer.is_valid():
            sessie = serializer.save(begeleider=request.user, school=leerling_instance.school)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
    
@authentication_classes([JWTAuthentication])
@permission_classes([IsAuthenticated])
class AddSessieAPIView_2(APIView):
    def post(self, request):
        # Create a mutable copy of the request data
        data = request.data.copy()

        # Extract the Leerling ID from the request data and convert it to integer
        leerling_id = data.get('Leerling')
        if leerling_id:
            leerling_id = leerling_id[0]  # Assuming it's always one ID passed

        try:
            # Attempt to convert the ID to an integer
            leerling_id = int(leerling_id)
        except (TypeError, ValueError):
            return Response({"error": "Invalid Leerling ID."}, status=status.HTTP_400_BAD_REQUEST)

        try:
            # Fetch the Leerling instance using the provided ID
            leerling_instance = Leerling.objects.get(id=leerling_id)
        except Leerling.DoesNotExist:
            return Response({"error": "Leerling not found."}, status=status.HTTP_404_NOT_FOUND)
        
        # Initialize the serializer with the request data
        serializer = SessieSerializer_2(data=data)
        
        # Validate the data
        if serializer.is_valid():
            # Save the session instance if the data is valid
            sessie = serializer.save(begeleider=request.user, school=leerling_instance.school)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            # Print and return the errors if validation fails
            print(serializer.errors)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    


@authentication_classes([JWTAuthentication])
@permission_classes([IsAuthenticated])
class UpdateSessieAPIView(APIView):
    def put(self, request, sessie_id):   # sessie_id is the ID of the Sessie to be updated
        try:
            sessie = Sessie.objects.get(id=sessie_id)
        except Sessie.DoesNotExist:
            return Response({"error": "Sessie not found"}, status=status.HTTP_404_NOT_FOUND)

        # Ensure the authenticated user has the right to update this Sessie
        # You might have other logic for this
        if request.user != sessie.begeleider:
            return Response({"error": "Unauthorized"}, status=status.HTTP_403_FORBIDDEN)

        data = request.data.copy()

        # You may need similar logic to the POST request to handle associated data
        # For example, to handle 'Leerling' foreign key, etc.
        # Add that here if necessary

        serializer = SessieSerializer_2(instance=sessie, data=data, partial=True)  # partial=True allows for partial updates

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)





        

Login/templates/Login/add_materiaal.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <h1>Upload Materiaal</h1>
    <form method="POST" class="post-form" enctype="multipart/form-data">  
        <div class="form-group">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit" class="btn btn-primary">verstuur</button>
    </div>
    </form>
</div>
{% endblock %}

Login/templates/Login/add_sessie.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Maak een logboek</h1>
    <form method="POST" action = '{% url 'Login:form' %}'>
        {% csrf_token %}
        <div class="form-group">
            <label for="id_Leerling">Leerling:</label>
            <input list="leerlingen" id="id_Leerling" name="Leerling" class="form-control">
            <datalist id="leerlingen">
                
            </datalist>

            <label for="id_inzicht">Inzicht:</label>
            <select id="id_inzicht" name="inzicht" class="form-control">
                <option value=""></option>
                {% for i in '12345' %}
                    <option value="{{ i }}">{{ i }}</option>
                {% endfor %}
            </select>

            <label for="id_kennis">Kennis:</label>
            <select id="id_kennis" name="kennis" class="form-control">
                <option value=""></option>
                {% for i in '12345' %}
                    <option value="{{ i }}">{{ i }}</option>
                {% endfor %}
            </select>
            <label for="id_werkhouding">Werkhouding:</label>
            <select id="id_werkhouding" name="werkhouding" class="form-control">
                <option value=""></option>
                {% for i in '12345' %}
                    <option value="{{ i }}">{{ i }}</option>
                {% endfor %}
            </select>



            <label for="id_extra">Extra:</label>
            <textarea id="id_extra" name="extra" class="form-control"></textarea>

         

            <label for="id_vak">Vak:</label>
            <input list="vakken" id="id_vak" name="vak" class="form-control">
            <datalist id="vakken">
                {% for vak in vaks %}
                    <option value="{{ vak.naam }}"> {{ vak.naam }}</option>
                {% endfor %}
            </datalist>

        </div>
        <button type="submit" class="btn btn-primary">Opslaan</button>
    </form>
</div>
{% block javascript %}
<script>
    let timeout = null;

    function fill_in(data) {
        var datalist = document.getElementById('leerlingen');
        datalist.innerHTML = ""; // clear the datalist before adding new options
        data.forEach(item => {
            var option = document.createElement('option');
            option.value = item.naam + " " + item.achternaam;
            option.text = item.naam + " " + item.achternaam;
            datalist.appendChild(option);
        });
    }

    document.getElementById('id_Leerling').addEventListener('input', function(event) {
        clearTimeout(timeout); // clear the timeout if it's already set

        timeout = setTimeout(() => {
            var searchInput = document.getElementById('id_Leerling').value;
            var api_url = `{% url 'Login:api_student' %}?search-input=${searchInput}`;
            fetch(api_url, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': 'Token your_token_here'  // replace this with the actual token
                },
            })
            .then(response => response.json())
            .then(data => fill_in(data));
        }, 500); // delay of 500ms
    });

    // Link the datalist to the input field for autocomplete
    document.getElementById('id_Leerling').setAttribute('list', 'leerlingen');
</script>

{% endblock javascript %}

{% endblock %}

Login/templates/Login/add_student.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container">
    <h1>Voeg een leerling toe</h1>
    <form method="post">
        <div class="form-group">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit" class="btn btn-primary">Opslaan</button>
    </div>
    </form>
</div>
{% endblock %}

Login/templates/Login/delete_materiaal.html
{% extends 'base.html' %}

{% block content %}
  <h1>Bevestig verwijdering</h1>
  <p>Weet je zeker dat je alles wil verwijderen?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Ja, verwijder</button>
    <a href="{% url 'Login:materiaal_all' %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

Login/templates/Login/delete_sessie.html
{% extends 'base.html' %}

{% block content %}
  <h1>Bevestig verwijdering</h1>
  <p>Weet je zeker dat je alles wil verwijderen?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Ja, verwijder</button>
    <a href="{% url 'Login:sessie_detail' pk=sessie.pk %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

Login/templates/Login/report.html
{% extends 'base.html' %}




{% block content %}



<button class="btn btn-primary" type="button" id="pdfButton">Download pdf</button>
<div class="container" id="contentToPDF">
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card">
          <div class="card-body">
            <h1 class="card-title">{{ object.naam|title }} {{ object.achternaam|title}}</h1>
            <p class="card-text">
              <strong>School:</strong> {{ object.school }}<br>
              <strong>Niveau:</strong> {{ object.niveau }}<br>
              <strong>Klas:</strong> {{ object.klas }}<br>
              <strong>Email:</strong> {{ object.email }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <h2>Grafieken</h2>
  <div class="html2pdf__page-break ">
    <div class="chart-container " style="position: relative; height:40vh; width:80vw">
      <canvas id="kennisChart"></canvas>
    </div>
    <div class="chart-container html2pdf__page-break" style="position: relative; height:40vh; width:80vw">
      <canvas id="werkhoudingChart"></canvas>
    </div>
    <div class="chart-container " style="position: relative; height:40vh; width:80vw">
      <canvas id="inzichtChart"></canvas>
    </div>
    
  </div>
  
  <h2>Sessies</h2>
  {% for sessie in object.sessie_set.all %}

  <div class="card mb-3 {% if forloop.counter|divisibleby:2 %}html2pdf__page-break{% endif %}">
    <div class="card-header">
      <h5 class="card-title">{{ sessie.datum }}</h5>
      <h6 class="card-subtitle text-muted"><a href="{% url 'Login:student_detail' leerling.pk %}">{{sessie.Leerling.naam|title}} {{sessie.Leerling.achternaam|title}}</a></h6>
    </div>
    <div class="card-body d-flex flex-wrap">
      <div class="p-2">Begeleider: {{ sessie.begeleider }}</div>
      <div class="p-2">School: {{ sessie.Leerling.school }}</div>
      <div class="p-2">Niveau: {{ sessie.Leerling.niveau }}</div>
      <div class="p-2">Klas: {{ sessie.Leerling.klas }}</div>
      <div class="p-2">Vak: {{ sessie.vak }}</div>
      <div class="p-2">Inzicht: {{ sessie.inzicht }}</div>
      <div class="p-2">Kennis: {{ sessie.kennis }}</div>
      <div class="p-2">Werkhouding: {{ sessie.werkhouding }}</div>
    </div>
    <div class="card-footer">
      <h5 class="card-title">Extra Info</h5>
      <p class="card-text">{{ sessie.extra }}</p>
    </div>
  </div>
{% endfor %}


</div>


  


  {% block javascript %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script>
    $(document).ready(function () {
      console.log('document ready');
      var element = document.getElementById('contentToPDF');
      console.log('form: ', element);
      var mode =  {  mode: 'legacy' };
      var opt = {
        filename: "{{object.naam|title}}" + "" + "{{object.achternaam|title}} "+ '.pdf',
        pagebreak: mode,
        jsPDF: {orientation: 'portrait', unit: 'mm', format: 'A4', compressPDF: false},
        html2canvas: {scale:5}
      };
    
      $('#pdfButton').on('click', function () {
        // Add the class to adjust layout
        document.body.classList.add('left-align');
    
        // Generate the PDF
        html2pdf().from(element).set(opt).save().then(function() {
          // Once the PDF is generated, remove the class
          document.body.classList.remove('left-align');
        });
      });
    });
    
    

    console.log("{{ object.pk }}")
    $.ajax({
      url: "{% url 'Login:api_sessie' %}",
      data: {
        'leerling': "{{ object.pk }}",
      },
      type: 'get',
      dataType: 'json',
      success: function (data) {

      
        console.log(data);
        var sessies = data;

        // Initialize empty lists for kennis, werkhouding, inzicht
        var kennisList = [];
        var werkhoudingList = [];
        var inzichtList = [];

        // Loop through each session
        sessies.forEach(function (sessie) {
          // Add values to the respective lists
          kennisList.push(sessie.kennis);
          werkhoudingList.push(sessie.werkhouding);
          inzichtList.push(sessie.inzicht);
        });

        // Log the lists
        console.log("Kennis: ", kennisList);
        console.log("Werkhouding: ", werkhoudingList);
        console.log("Inzicht: ", inzichtList);
        var labels = data.map(function (sessie, index) {
          return "Sessie " + (index + 1);
        });

        function createChart(elementId, chartLabel, chartData) {
          new Chart(document.getElementById(elementId), {
            type: 'line',
            data: {
              labels: labels,
              datasets: [{
                label: chartLabel,
                data: chartData,
                backgroundColor: 'rgb(4, 50, 77)',
                fill: true,
                borderColor: 'rgb(255, 255, 255)',
                tension: 0.2
              }],
              options: {
                legend: {
                    display: false // this will hide the legend
                }
            }
        }});
        }

        createChart('kennisChart', 'Kennis', kennisList);
        createChart('werkhoudingChart', 'Werkhouding', werkhoudingList);
        createChart('inzichtChart', 'Inzicht', inzichtList);
      }
    });

  </script>

  {% endblock javascript %}

  {% endblock content %}

Login/templates/Login/sessie.html
{% extends 'base.html' %}

{% block title %}All Students{% endblock %}

{% block content %}
    <h1>All Students</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Student</th>
                <th>Employer</th>
                <th>Kennis/th>
                <th>Extra</th>
                <th>School</th>
            </tr>
        </thead>
        <tbody>
            {% for sessie in sessie %}
                <tr>
                    <td>{{ sessie.Leerling }}</td>
                    <td>{{ sessie.begeleider }}</td>
                    <td>{{ sessie.kennis }}</td>
                    <td>{{ sessie.extra }}</td>
                    <td>{{ sessie.School}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

Login/templates/Login/student_all.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container">
  <h1>Alle leerlingen</h1>
  
  <!-- Search form -->
  <form id="search-form" class="mb-3"> <!-- added mb-3 for some margin bottom -->
    <div class="form-group">
      <input type="text" name="search-input" id="search-input" class="form-control w-100" placeholder="Zoek op naam">
    </div>
  </form>

  <!-- Student cards here -->
  <div class="row" id="student-card-container">
    <!-- Will be populated with JS -->
  </div>
</div>


{% block javascript %}
<script>
// function to populate table
function populateTable(data) {
  var cardContainer = document.getElementById('student-card-container');
  // Clear the container
  cardContainer.innerHTML = '';

  // Populate the container with cards
  data.forEach(student => {
    var cardHTML = `
      <div class="col-sm-12 col-md-6 col-lg-4 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">${student.naam} ${student.achternaam}</h5>
            <p class="card-text">
              Email: ${student.email}<br>
              School: ${student.school.naam}
            </p>
            <a href="/Login/student/${student.id}" class="btn btn-primary">Details</a>
          </div>
        </div>
      </div>
    `;
    cardContainer.innerHTML += cardHTML;
  });
}


// Fetch all students when page loads
fetch(`{% url 'Login:api_student' %}`, {
  method: 'GET',
  headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Token your_token_here'  // replace this with the actual token
  },
})
.then(response => response.json())
.then(data => populateTable(data));

// Fetch students based on search
document.getElementById('search-input').addEventListener('input', function(event) {
  event.preventDefault();

  var searchInput = document.getElementById('search-input').value;

  fetch(`{% url 'Login:api_student' %}?search-input=${searchInput}`, {
      method: 'GET',
      headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Token your_token_here'  // replace this with the actual token
      },
  })
  .then(response => response.json())
  .then(data => populateTable(data));
});

</script>
{% endblock javascript %}
{% endblock %}

Login/templates/Login/update_materiaal.html
{% extends 'base.html' %}

{% block content %}
  <h1>Edit session</h1>
  
{% load crispy_forms_tags %}
<form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form |crispy }}
    <button type="submit" class="btn btn-primary">Sla wijzingen op</button>
  </form>
{% endblock %}